field: 0c5d5dd2-0868-4e92-a369-4de8c79d9202 # Recipe Instructions
fieldLayouts:
  375cd18b-65f6-48ca-9c0b-b0caefbdc91b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 600e750f-c033-47a6-b943-8e378f651e04 # Instruction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f6c8f133-fed5-42c8-9bb9-3c65fd700d95
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ddabf3ff-e8f9-4494-bdda-2e9aaf78fbe0
        userCondition: null
fields:
  600e750f-c033-47a6-b943-8e378f651e04: # Instruction
    columnSuffix: cizqfcgq
    contentColumnType: text
    fieldGroup: null
    handle: instruction
    instructions: null
    name: Instruction
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: 'Add your recipe steps'
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: list
name: List
sortOrder: 1
