fieldLayouts:
  f6ccea25-9c76-4dce-87b3-c39e7ad4c521:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c51774a4-cfd6-4593-b7c9-82e535aaae67
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 76d6ab0b-d1fd-491c-960c-ce6c74f9ab73
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 7a2c8e56-292b-430e-b3b4-9472060a48b6 # Comments
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
