fieldLayouts:
  3c1f2040-e879-41c2-a3eb-72a04427bd93:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e781755c-2b70-4ba1-a148-821e1bbc8f61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fae472b1-d526-4567-8a0a-f4821b7f8d20 # Card Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 318e4237-e952-456e-a0a5-e7d3bbb20bcb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8eeff1e3-4810-4aa5-a83e-43630265afdf # Card Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9772c07-772d-4f4d-9766-7907c18658ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: abe56bc6-a920-4f9f-8dfa-4527a48b0ad7 # Type of Dish
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 45ede00e-6eab-4316-934e-4a39a8c40bb2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e950dc98-3d45-44f5-9ba8-90852ca6de5e # Cooking Time
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e9e586e7-fe33-4288-813b-be993713295d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b822cda0-c08e-4106-8dd6-8e5142ca11e2 # Cooking Tip
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa38fddd-732e-4ca4-9126-e448c5821949
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 897c0904-c1f0-4527-bc4c-42e40ff69f9c # Short Dish Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87c76da7-560b-47e5-a7cc-5ad7d5c626ec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4d217a65-25b3-4f9a-b847-5e11e36c27b0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 80727c92-66de-48a4-bc22-7851caf5ef96 # Ingredient List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe441aae-7e3f-4da1-a58b-a5425e96274b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0c5d5dd2-0868-4e92-a369-4de8c79d9202 # Recipe Instructions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b50b9aea-4c30-4428-877e-aa909434206d
            userCondition: null
            warning: null
            width: 100
        name: Instructions
        uid: fdbf5637-39cd-4ad3-9e52-2757aad60ece
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 34900664-ae6b-4631-86db-36aa62e63cd8 # Cards
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
