fieldLayouts:
  fec63489-9120-49c2-8736-d3dbd3280527:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: dbd9b529-7f21-4378-bce7-b332cfff95ec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 175961c7-ef78-4eff-a912-95b293ed4cfa
        userCondition: null
handle: home
hasTitleField: false
name: home
section: de58d882-4f08-46e5-b351-b963ad47133f # home
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
