fieldLayouts:
  9b4fc336-83e5-4442-b8ac-0b887f91549c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d387d74f-1469-483c-b7c7-71a30023d52a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 047af35b-3fc7-442d-9e6f-f6a1b3ea3aa2
        userCondition: null
fs: cardimages
handle: cardImages
name: 'Card Images'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: cardimages
transformSubpath: ''
