fieldLayouts:
  b0454e63-2b52-4efa-bb86-64f78d322595:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: c459a75c-8314-40e3-bf7b-7588f12f3d80
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5477e9eb-adeb-49e2-82d0-469f6045162c
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 3
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
