columnSuffix: ghihygll
contentColumnType: integer(10)
fieldGroup: 97b39696-39d5-4c02-a9d8-7c992bca8c70 # Common
handle: cookingTimeMinutes
instructions: null
name: 'Cooking Time - Minutes'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
