columnSuffix: rrytzwpj
contentColumnType: string(40)
fieldGroup: 0f2aa2c7-172c-4904-a9f3-0911a7d852f1 # Home
handle: dishType
instructions: null
name: 'Dish Type'
searchable: false
settings:
  byteLimit: null
  charLimit: 10
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
