columnSuffix: null
contentColumnType: string
fieldGroup: 1d18599f-28bf-4c6b-bd5e-6cdbab818044 # Cards
handle: recipeInstructions
instructions: null
name: 'Recipe Instructions'
searchable: false
settings:
  contentTable: '{{%matrixcontent_recipeinstructions}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
