defaultPlacement: end
enableVersioning: true
handle: cards
name: Cards
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  5957fd25-68f5-48f7-9420-f145a9452018: # Bites.
    enabledByDefault: true
    hasUrls: true
    template: recipe/_entry.twig
    uriFormat: 'cards/{slug}'
type: channel
